version: '3.8'

services:
  path-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes: 
      - ./pdfs:/tmp
      - ./app/templates:/app/templates
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - SLEEP_TIME=1                # Temps en secondes entre chaque requêtes
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes: 
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080